mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from pokerMain import views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pokerMain.urls")),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    #path('profile/', user_views.profilepage, name='profile'),

]
urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pokerMain/urls.py
from . import views
from django.urls import path

app_name = 'pokerMain'
urlpatterns = [
    path('', views.index, name="index"),
    path('play/', views.play_game, name="play_game"),
    path('play/raise', views.clicked_raise, name='clicked_raise'),
    path('play/fold', views.clicked_fold, name='clicked_fold'),
    path('report/', views.report_bug, name='report_bug')



]

pokerMain/models.py
from django.db import models

# Create your models here.


class Cards(models.Model):

    def __str__(self):
        return self.card_name

    card_name = models.CharField(max_length=100)
    value = models.CharField(max_length=2)
    suit = models.CharField(max_length=1)
    image = models.ImageField(upload_to='images', default='image/none/noimg.jpg')


class SB_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class BB_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class utg_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class utg1_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class lj_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class hj_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class co_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class btn_100bb(models.Model):

    def __str__(self):
        return self.hand_name

    hand_name = models.CharField(max_length=100)
    suited = models.CharField(max_length=3)
    card1 = models.CharField(max_length=2)
    card2 = models.CharField(max_length=2)
    action = models.CharField(max_length=6)


class scoring(models.Model):
    attempts = models.IntegerField()
    correct = models.IntegerField()
    score = models.FloatField()


class report(models.Model):
    Name = models.CharField(max_length=100)
    Email = models.CharField(max_length=100)
    Bug = models.TextField(max_length=500)

pokerMain/forms.py
from django import forms
from django.forms import Textarea

from .models import report


class ContactForm(forms.ModelForm):
    class Meta:
        model = report
        fields = ['Name', 'Email', 'Bug']
        widgets = {
            'Bug': Textarea(attrs={"rows": 5, "cols": 32})
        }

pokerMain/views.py
from django.shortcuts import render, redirect

from .forms import ContactForm
from .models import Cards, utg_100bb, utg1_100bb, lj_100bb, hj_100bb, co_100bb, btn_100bb, scoring
import random
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):

    new_scoring = scoring(attempts=0, correct=0, score=0)
    new_scoring.save()
    model_id = new_scoring.id
    return render(request, 'pokerMain/index.html', {'model_id': model_id})

@login_required()
def play_game(request):
    random.randint(1, 52)
    # assigning random cards
    rand1 = random.randint(1, 52)
    rand2 = random.randint(1, 52)
    while rand1 == rand2:
        rand2 = random.randint(1, 52)
    card1 = Cards.objects.get(id=rand1)
    card2 = Cards.objects.get(id=rand2)

    # checking suits of cards, so we can check if hand is suited or not
    if card1.suit == card2.suit:
        suited = 'yes'
    else:
        suited = 'no'

    action = ''
    hands = ''
    # assigning random position each time game is played
    rand_position = random.randint(3, 8)
    if rand_position == 1:
        position_name = 'SB'
    if rand_position == 2:
        position_name = 'BB'
    if rand_position == 3:
        hands = utg_100bb.objects.all()
        position_name = 'UTG'
        table = '/images/images/poker table UTG.jpg'
    if rand_position == 4:
        hands = utg1_100bb.objects.all()
        position_name = 'UTG1'
        table = '/images/images/poker table UTG1.jpg'
    if rand_position == 5:
        hands = lj_100bb.objects.all()
        position_name = 'LJ'
        table = '/images/images/poker table LJ.jpg'
    if rand_position == 6:
        hands = hj_100bb.objects.all()
        position_name = 'HJ'
        table = '/images/images/poker table HJ.jpg'
    if rand_position == 7:
        hands = co_100bb.objects.all()
        position_name = 'CO'
        table = '/images/images/poker table CO.jpg'
    if rand_position == 8:
        hands = btn_100bb.objects.all()
        position_name = 'BTN'
        table = '/images/images/poker table BTN.jpg'

    for x in hands:
        # print(x.hand_name)
        # print(x.action)

        if suited == 'yes':
            if x.suited == 'yes':
                if card1.value == x.card1:
                    if card2.value == x.card2:
                        print('MATCH FOUND')
                        print(x.hand_name)
                        action = x.action
                        break

        if suited == 'yes':
            if x.suited == 'yes':
                if card1.value == x.card2:
                    if card2.value == x.card1:
                        print('MATCH FOUND')
                        print(x.hand_name)
                        action = x.action
                        break

        if suited == 'no':
            if x.suited == 'no':
                if card1.value == x.card2:
                    if card2.value == x.card1:
                        print('MATCH FOUND')
                        print(x.hand_name)
                        action = x.action
                        break

        if suited == 'no':
            if x.suited == 'no':
                if card1.value == x.card1:
                    if card2.value == x.card2:
                        print('MATCH FOUND')
                        print(x.hand_name)
                        action = x.action
                        break
        #print(x.suited)
        #print(card1)
        #print(card2)
        #print(x.hand_name)


    request.session['card1'] = card1.id
    request.session['card2'] = card2.id
    request.session['action'] = action
    request.session['table'] = table



    recent_score = scoring.objects.latest('id')

    attempts = recent_score.attempts
    correct = recent_score.correct
    score = recent_score.score
    score = score * 100
    score = round(score, 1)
    print(score)

    print("Card1 ID: " + str(card1.id))
    print("Card2 ID: " + str(card2.id))
    print("Action: " + str(action))
    print("Attempts:  " + str(attempts))
    print("Correct:  " + str(correct))
    print("Score:  " + str(score))

    return render(request, 'pokerMain/play.html', {'card1': card1, 'card2': card2, 'position_name': position_name,
                                                   'action': action, 'table': table, 'attempts': attempts,
                                                   'correct': correct, 'score': score})

@login_required()
def clicked_raise(request):
    action = request.session['action']
    card1_id = request.session['card1']
    card2_id = request.session['card2']
    table = request.session['table']

    print("Result Card1 ID: " + str(card1_id))
    print("Result Card2 ID: " + str(card2_id))
    print("final_result: " + action)

    newcard1 = Cards.objects.get(id=card1_id)
    newcard2 = Cards.objects.get(id=card2_id)

    recent_score = scoring.objects.latest('id')
    current_attempts= recent_score.attempts
    current_correct = recent_score.correct
    current_score = recent_score.score

    if action == 'raise':
        result = 'correct'
        current_correct += 1
    else:
        result = 'incorrect'

    if request.GET.get('Next Hand') == 'Next Hand':
        print('user clicked summary')

        current_attempts += 1
        current_score = current_correct / current_attempts

        recent_score.correct = current_correct
        recent_score.attempts = current_attempts
        recent_score.score = current_score
        recent_score.save()

        print("Attempts:  " + str(current_attempts))
        print("Correct:  " + str(current_correct))
        print("Score:  " + str(current_score))


        return redirect('pokerMain:play_game')

    return render(request, 'pokerMain/result.html', {'newcard1': newcard1, 'newcard2': newcard2, 'result': result,
                                                     'table': table})
@login_required()
def clicked_fold(request):
    action = request.session['action']
    card1_id = request.session['card1']
    card2_id = request.session['card2']
    table = request.session['table']

    print("Result Card1 ID: " + str(card1_id))
    print("Result Card2 ID: " + str(card2_id))
    print("final_result: " + action)

    newcard1 = Cards.objects.get(id=card1_id)
    newcard2 = Cards.objects.get(id=card2_id)

    recent_score = scoring.objects.latest('id')
    current_attempts = recent_score.attempts
    current_correct = recent_score.correct
    current_score = recent_score.score

    if action == 'fold':
        result = 'correct'
        current_correct += 1
    else:
        result = 'incorrect'

    if request.GET.get('Next Hand') == 'Next Hand':
        print('user clicked summary')
        current_attempts += 1
        current_score = current_correct / current_attempts

        recent_score.correct = current_correct
        recent_score.attempts = current_attempts
        recent_score.score = current_score
        recent_score.save()

        print("Attempts:  " + str(current_attempts))
        print("Correct:  " + str(current_correct))
        print("Score:  " + str(current_score))
        return redirect('pokerMain:play_game')

    return render(request, 'pokerMain/result.html', {'newcard1': newcard1, 'newcard2': newcard2, 'result': result,
                                                     'table':table})
@login_required()
def report_bug(request):
    form = ContactForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('pokerMain:play_game')

    return render(request, 'pokerMain/report.html', {'form': form})

@login_required()
def add_hands(request):
    # AA - A2s
    hand = btn_100bb(hand_name='AA', suited='no', card1='A', card2='A', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='AKs', suited='yes', card1='A', card2='K', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='AQs', suited='yes', card1='A', card2='Q', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='AJs', suited='yes', card1='A', card2='J', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A10s', suited='yes', card1='A', card2='10', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A9s', suited='yes', card1='A', card2='9', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A8s', suited='yes', card1='A', card2='8', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A7s', suited='yes', card1='A', card2='7', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A6s', suited='yes', card1='A', card2='6', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A5s', suited='yes', card1='A', card2='5', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A4s', suited='yes', card1='A', card2='4', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A3s', suited='yes', card1='A', card2='3', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A2s', suited='yes', card1='A', card2='2', action='raise')
    hand.save()

    # AKo - A2o
    hand = btn_100bb(hand_name='AKo', suited='no', card1='A', card2='K', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='AKos', suited='no', card1='A', card2='Q', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='AJo', suited='no', card1='A', card2='J', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A10o', suited='no', card1='A', card2='10', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A9o', suited='no', card1='A', card2='9', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A8o', suited='no', card1='A', card2='8', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A7o', suited='no', card1='A', card2='7', action='raise')
    hand.save()

    hand = btn_100bb(hand_name='A6o', suited='no', card1='A', card2='6', action='fold')
    hand.save()

pokerMain/templates/pokerMain/addhands.html
<h1>HANDS ADDED</h1>

pokerMain/templates/pokerMain/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<style>
    .background1{
        background-image: url("../../../images/images/poker_background.jpg");
        background-repeat: no-repeat;
        background-size: cover;

    }
</style>
<nav class="navbar navbar-dark">
    <a href="{% url 'pokerMain:index' %}" class="navbar-brand">CHOWDER POKER</a>
    <div class="navbar">
        <a href="{% url 'pokerMain:index' %}" class="nav-item nav-link" style="color: white">HOME</a>
        {% if user.is_authenticated %}
            <a href="{% url 'pokerMain:play_game'%}" class="nav-item nav-link" style="color: white">PLAY</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link" style="color: white">LOGOUT</a>
        {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link" style="color: white">LOGIN</a>
            <a href="{% url 'register' %}" class="nav-item nav-link" style="color: white">REGISTER</a>
        {% endif %}
    </div>
</nav>
<body class="background1">
{% block body %}
    background-image: url("../images/images/poker table UTG.jpg");
{% endblock %}
</body>
</html>

pokerMain/templates/pokerMain/bogus.html
 <div class="raise">
            <button type="button" style="width: 250%; font-size: 200%; font-weight: bold"
                    class="btn btn-success btn-lg" value="Raise" name="Raise" type="submit">RAISE</button>
        </div>
        <div class="fold">
            <button type="button" style="width: 250%; font-size: 200%; font-weight: bold"
                    class="btn btn-danger btn-lg" value="Fold" name="Fold" type="submit">FOLD</button>
        </div>






   <button style="width: 50%; height: 100%; margin-right: 5%; margin-left: 35%; margin-bottom: 1%;
             font-weight: bold" class="btn btn-success btn-lg" value="Raise" name="Raise" type="submit">RAISE</button>

            <button style="width: 50%; height: 100%; margin-left: 5%; margin-right: 35%; margin-bottom: 1%;
            font-weight: bold" class="btn btn-danger btn-lg" value="Fold" name="Fold" type="submit">FOLD</button>



  <form method='get' action='#'>
                <input  class="btn btn-success btn-lg"  style="width: 150%; height: 100%;  margin-left: 1250%; margin-bottom: 1%;
                 font-weight: bold" type="submit" value="Raise" name="Raise"/>
  </form>

 <form method='get' action='#'>
                <input  class="btn btn-danger btn-lg"  style="width: 150%; height: 100%; margin-left: 1800%; margin-bottom: 1%;
                 font-weight: bold" type="submit" value="Fold"  name="Fold"/>
 </form>

pokerMain/templates/pokerMain/play.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Play</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <nav class="navbar navbar-dark">
    <a href="{% url 'pokerMain:index' %}" class="navbar-brand">CHOWDER POKER</a>
    <div class="navbar">
        <a href="{% url 'pokerMain:index' %}" class="nav-item nav-link" style="color: white">HOME</a>
        {% if user.is_authenticated %}
            <a href="{% url 'pokerMain:play_game'%}" class="nav-item nav-link" style="color: white">PLAY</a>
            <a href="{% url 'pokerMain:report_bug' %}" class="nav-item nav-link" style="color: white">REPORT BUG</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link" style="color: white">LOGOUT</a>
        {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link" style="color: white">LOGIN</a>
            <a href="{% url 'register' %}" class="nav-item nav-link" style="color: white">REGISTER</a>
        {% endif %}
    </div>
</nav>
</head>
<style>
     html, body {
         background-color: black;
         width: 100%;
         height: 100%;
         overflow: hidden;
      }

.image1 {
    position: static;
    top: 0;
    left: 0;

    max-width: 80%;
    max-height: 80%;
    display: block;
    margin-left: auto;
    margin-right: auto;


}
.image2 {
    position: absolute;
    left: 44%;
    bottom:35%;
    height: 18.5%;
    width: 6.1%;

}
.image3 {
    position: absolute;
    left: 50%;
    bottom: 35%;
    height: 18.5%;
    width: 6.10%;


}
.center{
    width: 100%;
    position: absolute;
    display: block;


}
.button1{
    flex-direction: row;
    display: flex;
    justify-content: flex-start;
    position: absolute;
    left: 2.25%;
    top: 38%
}
.button2{
    flex-direction: column;
    display: flex;
    justify-content: flex-start;
    position: absolute;
    left: 2.5%;
    top: 51%;



}
.labels{
    flex-direction: column;
    display: flex;
    justify-content: flex-start;
    position: absolute;
    right: 2.5%;
    top: 40%;
    color: white;
    font-size: 250%;
 }

</style>
<body>
{% block body %}

<div class="center">
    <div>
        <img class="image1" src="{{ table }}" />
            <div>
                <img class="image2" src="{{ card1.image.url }}" />
            </div>
            <div>
                <img class="image3" src="{{ card2.image.url }}" />
            </div>

            <div class="container">
                <div class="button1">
                    <a href="{% url 'pokerMain:clicked_raise' %}">
                        <button style="width: 110%; height: 130%; margin-left: 150%; margin-right: 5%;  margin-bottom: 1%;
                        font-weight: bold" class="btn btn-success btn-lg" value="Raise" name="Raise" type="submit">RAISE</button>
                    </a>
                </div>

                <div class="button2">
                    <a href="{% url 'pokerMain:clicked_fold' %}">
                        <button style="width: 116%; height: 130%; margin-left: 150%; margin-right: 40%; margin-bottom: 1%;
                        font-weight: bold" class="btn btn-danger btn-lg" value="Fold" name="Fold" type="submit">FOLD</button>
                    </a>
                </div>
            </div>
            <div class="labels">
                <b>Correct: {{ correct }}</b>
                <b>Attempts: {{ attempts }}</b>
                <b>Score: {{ score }}%</b>

            </div>
        </div>
</div>
{% endblock %}
</body>
</html>

pokerMain/templates/pokerMain/report.html
{% extends 'pokerMain/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %} Report a bug {% endblock title %}
</head>
<body>
{% block body %}
 <div class="container" style="padding-top: 5%">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                 <div class="card">
                    <div class="card-header bg-dark text-white">
                        <div class="card-title">
                            Report a bug
                        </div>
                    </div>
                     <div class="card-body">
                         <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                              {% endfor  %}
                            <button type="submit" class="btn btn-dark">Submit</button>
                          </form>
                     </div>
                 </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

pokerMain/templates/pokerMain/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Result</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <nav class="navbar navbar-dark">
    <a href="{% url 'pokerMain:index' %}" class="navbar-brand">CHOWDER POKER</a>
    <div class="navbar">
        <a href="{% url 'pokerMain:index' %}" class="nav-item nav-link" style="color: white">HOME</a>
        {% if user.is_authenticated %}
            <a href="{% url 'pokerMain:play_game'%}" class="nav-item nav-link" style="color: white">PLAY</a>
            <a href="{% url 'pokerMain:report_bug' %}" class="nav-item nav-link" style="color: white">REPORT BUG</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link" style="color: white">LOGOUT</a>
        {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link" style="color: white">LOGIN</a>
            <a href="{% url 'register' %}" class="nav-item nav-link" style="color: white">REGISTER</a>
        {% endif %}
    </div>
</nav>
</head>
<style>
     html, body {
         background-color: black;
         width: 100%;
         height: 100%;
         overflow: hidden;
      }

.image1 {
    position: static;
    top: 0;
    left: 0;

    max-width: 80%;
    max-height: 80%;
    display: block;
    margin-left: auto;
    margin-right: auto;


}
.image2 {
    position: absolute;
     left: 44%;
    bottom:35%;
    height: 18.5%;
    width: 6.1%;


}
.image3 {
    position: absolute;
    left: 50%;
    bottom: 35%;
    height: 18.5%;
    width: 6.10%;

}
.center{
    width: 100%;
    position: absolute;
    display: block;
}

.button1{
    flex-direction: row;
    display: flex;
    justify-content: flex-start;
    position: absolute;
    left: 6.5%;
    top: 45%
}
.button2{
    flex-direction: row;
    display: flex;
    justify-content: flex-start;
    position: absolute;
    left: 8.5%;
    top: 50%;
}
.correct{
    position: absolute;
    left: 41%;
    top: 35%;
    height: 10%;
    length: 10%
}
.incorrect{
    position: absolute;
    left: 41%;
    top: 35%;
    height: 10%;
    length: 10%
}

</style>
<body>
{% block body %}
<div class="center">
    <div>
        <img class="image1" src="{{ table }}" />
            <div>
                <img class="image2" src="{{ newcard1.image.url }}" />
            </div>
            <div>
                <img class="image3" src="{{ newcard2.image.url }}" />
            </div>
            <div class="container">
            <div class="button1">
                <form method='get' action='#'>
                    {% csrf_token %}
                    <input class="btn btn-primary btn-lg"  style="width: 110%; height: 130%;
                     font-weight: bold" type="submit" value="Next Hand" name="Next Hand"/>
                </form>
            </div>
                {% if result == 'correct' %}
                    <img class="correct" src="/images/images/correct.png" />
                {% endif %}

                {% if result == 'incorrect' %}
                    <img class="incorrect" src="/images/images/incorrect.png" />
                {% endif %}

        </div>
    </div>
</div>




{% endblock %}
</body>
</html>